# Generated by Django 4.1.3 on 2022-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status", name="name", field=models.CharField(max_length=50),
        ),
    ]
