# Generated by Django 4.1.3 on 2022-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0002_alter_status_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
