# Generated by Django 4.1.3 on 2022-11-08 21:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0003_news_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=tinymce.models.HTMLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
