# Generated by Django 4.1.3 on 2022-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0007_alter_news_slug_alter_news_title"),
    ]

    operations = [
        migrations.RenameField(model_name="news", old_name="slug", new_name="url",),
        migrations.AddField(
            model_name="news",
            name="docno",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="news",
            name="published_date",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
