# Generated by Django 4.1.3 on 2022-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doccharacterizationapp",
            "0008_rename_slug_news_url_news_docno_news_published_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="news", name="published_date", field=models.IntegerField(),
        ),
    ]
