# Generated by Django 4.1.3 on 2022-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0009_alter_news_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news", name="docno", field=models.CharField(max_length=15),
        ),
    ]
