# Generated by Django 4.1.3 on 2022-11-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doccharacterizationapp", "0010_alter_news_docno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news", old_name="lead", new_name="headline",
        ),
    ]
